---
test:
  exceptions: 1
  trace: 1
  encoding: UTF-8
  connection_timeout: 60
  stream_context: false
  location: https://83.218.157.188/test/khaosids.exe/soap/IKosWeb
  uri: http://tempuri.org/
  wsdl: https://83.218.157.188/test/khaosids.exe/wsdl/IKosWeb?wsdl
prod:
  exceptions: 1
  trace: 1
  encoding: UTF-8
  connection_timeout: 30
  stream_context: false
  location: https://83.218.157.188/test/khaosids.exe/soap/IKosWeb
  uri: http://tempuri.org/
  wsdl: https://83.218.157.188/test/khaosids.exe/wsdl/IKosWeb?wsdl
...
